#pragma once

/** @file c_error.h
    @brief The C API error values and utilities.
**/

#include <one/arcus/c_platform.h>

#ifdef __cplusplus
extern "C" {
#endif

// Note - when adding errors:
//    1. Never change an existing number mapping.
//    2. Add the new error symbol to the error_text function in error.cpp.
typedef enum OneError {
    ONE_ERROR_NONE = 0,
    ONE_ERROR_ARRAY_ALLOCATION_FAILED = 100,
    ONE_ERROR_ARRAY_POSITION_OUT_OF_BOUNDS = 101,
    ONE_ERROR_ARRAY_WRONG_TYPE_IS_EXPECTING_ARRAY = 102,
    ONE_ERROR_ARRAY_WRONG_TYPE_IS_EXPECTING_BOOL = 103,
    ONE_ERROR_ARRAY_WRONG_TYPE_IS_EXPECTING_INT = 104,
    ONE_ERROR_ARRAY_WRONG_TYPE_IS_EXPECTING_OBJECT = 105,
    ONE_ERROR_ARRAY_WRONG_TYPE_IS_EXPECTING_STRING = 106,
    ONE_ERROR_CLIENT_NOT_INITIALIZED = 200,
    ONE_ERROR_CODEC_HEADER_LENGTH_TOO_SMALL = 300,
    ONE_ERROR_CODEC_HEADER_LENGTH_TOO_BIG = 301,
    ONE_ERROR_CODEC_DATA_LENGTH_TOO_SMALL_FOR_HEADER = 302,
    ONE_ERROR_CODEC_DATA_LENGTH_TOO_SMALL_FOR_PAYLOAD = 303,
    ONE_ERROR_CODEC_EXPECTED_DATA_LENGTH_TOO_BIG = 304,
    ONE_ERROR_CODEC_INVALID_MESSAGE_PAYLOAD_SIZE_TOO_BIG = 305,
    ONE_ERROR_CODEC_INVALID_HEADER = 306,
    ONE_ERROR_CODEC_TRYING_TO_ENCODE_UNSUPPORTED_OPCODE = 307,
    ONE_ERROR_CONNECTION_UNINITIALIZED = 400,
    ONE_ERROR_CONNECTION_HANDSHAKE_TIMEOUT = 401,
    ONE_ERROR_CONNECTION_HEALTH_TIMEOUT = 402,
    ONE_ERROR_CONNECTION_HELLO_INVALID = 403,
    ONE_ERROR_CONNECTION_HELLO_MESSAGE_HEADER_TOO_BIG = 404,
    ONE_ERROR_CONNECTION_HELLO_MESSAGE_RECEIVE_FAILED = 405,
    ONE_ERROR_CONNECTION_HELLO_MESSAGE_REPLY_INVALID = 406,
    ONE_ERROR_CONNECTION_HELLO_MESSAGE_SEND_FAILED = 407,
    ONE_ERROR_CONNECTION_HELLO_RECEIVE_FAILED = 408,
    ONE_ERROR_CONNECTION_HELLO_SEND_FAILED = 409,
    ONE_ERROR_CONNECTION_HELLO_TOO_BIG = 410,
    ONE_ERROR_CONNECTION_HELLO_VERSION_MISMATCH = 411,
    ONE_ERROR_CONNECTION_MESSAGE_RECEIVE_FAILED = 412,
    ONE_ERROR_CONNECTION_READ_TOO_BIG_FOR_STREAM = 413,
    ONE_ERROR_CONNECTION_OUT_MESSAGE_TOO_BIG_FOR_STREAM = 414,
    ONE_ERROR_CONNECTION_QUEUE_EMPTY = 415,
    ONE_ERROR_CONNECTION_QUEUE_INSUFFICIENT_SPACE = 416,
    ONE_ERROR_CONNECTION_OUTGOING_QUEUE_INSUFFICIENT_SPACE = 417,
    ONE_ERROR_CONNECTION_INCOMING_QUEUE_INSUFFICIENT_SPACE = 418,
    ONE_ERROR_CONNECTION_RECEIVE_BEFORE_SEND = 419,
    ONE_ERROR_CONNECTION_RECEIVE_FAIL = 420,
    ONE_ERROR_CONNECTION_SEND_FAIL = 421,
    ONE_ERROR_CONNECTION_TRY_AGAIN = 422,
    ONE_ERROR_CONNECTION_UNKNOWN_STATUS = 423,
    ONE_ERROR_CONNECTION_UPDATE_AFTER_ERROR = 424,
    ONE_ERROR_CONNECTION_UPDATE_READY_FAIL = 425,
    ONE_ERROR_MESSAGE_ALLOCATION_FAILED = 500,
    ONE_ERROR_MESSAGE_CALLBACK_IS_NULLPTR = 501,
    ONE_ERROR_MESSAGE_IS_NULLPTR = 502,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_ALLOCATED = 503,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_LIVE_STATE = 504,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_METADATA = 505,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_SOFT_STOP = 506,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_HOST_INFORMATION = 507,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_APPLICATION_INSTANCE_INFORMATION =
        508,
    ONE_ERROR_MESSAGE_OPCODE_NOT_MATCHING_EXPECTING_APPLICATION_INSTANCE_STATUS = 509,
    ONE_ERROR_MESSAGE_OPCODE_NOT_SUPPORTED = 510,
    ONE_ERROR_MESSAGE_OPCODE_PAYLOAD_NOT_EMPTY = 511,
    ONE_ERROR_OBJECT_ALLOCATION_FAILED = 600,
    ONE_ERROR_OBJECT_KEY_NOT_FOUND = 601,
    ONE_ERROR_OBJECT_KEY_IS_NULLPTR = 602,
    ONE_ERROR_OBJECT_WRONG_TYPE_IS_EXPECTING_ARRAY = 603,
    ONE_ERROR_OBJECT_WRONG_TYPE_IS_EXPECTING_BOOL = 604,
    ONE_ERROR_OBJECT_WRONG_TYPE_IS_EXPECTING_INT = 605,
    ONE_ERROR_OBJECT_WRONG_TYPE_IS_EXPECTING_OBJECT = 606,
    ONE_ERROR_OBJECT_WRONG_TYPE_IS_EXPECTING_STRING = 607,
    ONE_ERROR_PAYLOAD_KEY_NOT_FOUND = 700,
    ONE_ERROR_PAYLOAD_KEY_IS_NULLPTR = 701,
    ONE_ERROR_PAYLOAD_PARSE_FAILED = 702,
    ONE_ERROR_PAYLOAD_VAL_IS_NULLPTR = 703,
    ONE_ERROR_PAYLOAD_WRONG_TYPE_IS_EXPECTING_ARRAY = 704,
    ONE_ERROR_PAYLOAD_WRONG_TYPE_IS_EXPECTING_BOOL = 705,
    ONE_ERROR_PAYLOAD_WRONG_TYPE_IS_EXPECTING_INT = 706,
    ONE_ERROR_PAYLOAD_WRONG_TYPE_IS_EXPECTING_OBJECT = 707,
    ONE_ERROR_PAYLOAD_WRONG_TYPE_IS_EXPECTING_STRING = 708,
    ONE_ERROR_SERVER_ALLOCATION_FAILED = 800,
    ONE_ERROR_SERVER_ALREADY_INITIALIZED = 801,
    ONE_ERROR_SERVER_ALREADY_LISTENING = 802,
    ONE_ERROR_SERVER_RETRYING_LISTEN = 803,
    ONE_ERROR_SERVER_CALLBACK_IS_NULLPTR = 804,
    ONE_ERROR_SERVER_CONNECTION_IS_NULLPTR = 805,
    ONE_ERROR_SERVER_CONNECTION_NOT_READY = 806,
    ONE_ERROR_SERVER_MESSAGE_IS_NULLPTR = 807,
    ONE_ERROR_SERVER_SOCKET_ALLOCATION_FAILED = 808,
    ONE_ERROR_SERVER_SOCKET_NOT_INITIALIZED = 809,
    ONE_ERROR_SERVER_SOCKET_IS_NULLPTR = 810,
    ONE_ERROR_SOCKET_ACCEPT_NON_BLOCKING_FAILED = 900,
    ONE_ERROR_SOCKET_ACCEPT_UNINITIALIZED = 901,
    ONE_ERROR_SOCKET_ADDRESS_FAILED = 902,
    ONE_ERROR_SOCKET_AVAILABLE_FAILED = 903,
    ONE_ERROR_SOCKET_BIND_FAILED = 904,
    ONE_ERROR_SOCKET_CLOSE_FAILED = 905,
    ONE_ERROR_SOCKET_CONNECT_FAILED = 906,
    ONE_ERROR_SOCKET_CONNECT_NON_BLOCKING_FAILED = 907,
    ONE_ERROR_SOCKET_CONNECT_UNINITIALIZED = 908,
    ONE_ERROR_SOCKET_CREATE_FAILED = 909,
    ONE_ERROR_SOCKET_LISTEN_FAILED = 910,
    ONE_ERROR_SOCKET_LISTEN_NON_BLOCKING_FAILED = 911,
    ONE_ERROR_SOCKET_RECEIVE_FAILED = 912,
    ONE_ERROR_SOCKET_SELECT_FAILED = 913,
    ONE_ERROR_SOCKET_SELECT_UNINITIALIZED = 914,
    ONE_ERROR_SOCKET_SEND_FAILED = 915,
    ONE_ERROR_SOCKET_SOCKET_OPTIONS_FAILED = 916,
    ONE_ERROR_SOCKET_SYSTEM_CLEANUP_FAIL = 917,
    ONE_ERROR_SOCKET_SYSTEM_INIT_FAIL = 918,
    ONE_ERROR_VALIDATION_ARRAY_IS_NULLPTR = 1000,
    ONE_ERROR_VALIDATION_CALLBACK_IS_NULLPTR = 1001,
    ONE_ERROR_VALIDATION_CAPACITY_IS_NULLPTR = 1002,
    ONE_ERROR_VALIDATION_CODE_IS_NULLPTR = 1003,
    ONE_ERROR_VALIDATION_CONNECTION_IS_NULLPTR = 1004,
    ONE_ERROR_VALIDATION_DATA_IS_NULLPTR = 1005,
    ONE_ERROR_VALIDATION_DESTINATION_IS_NULLPTR = 1006,
    ONE_ERROR_VALIDATION_EMPTY_IS_NULLPTR = 1007,
    ONE_ERROR_VALIDATION_KEY_IS_NULLPTR = 1008,
    ONE_ERROR_VALIDATION_MAP_IS_NULLPTR = 1009,
    ONE_ERROR_VALIDATION_MESSAGE_IS_NULLPTR = 1010,
    ONE_ERROR_VALIDATION_MODE_IS_NULLPTR = 1011,
    ONE_ERROR_VALIDATION_NAME_IS_NULLPTR = 1012,
    ONE_ERROR_VALIDATION_OBJECT_IS_NULLPTR = 1013,
    ONE_ERROR_VALIDATION_RESULT_IS_NULLPTR = 1014,
    ONE_ERROR_VALIDATION_SERVER_IS_NULLPTR = 1015,
    ONE_ERROR_VALIDATION_SOCKET_IS_NULLPTR = 1016,
    ONE_ERROR_VALIDATION_SOURCE_IS_NULLPTR = 1017,
    ONE_ERROR_VALIDATION_STATUS_IS_NULLPTR = 1018,
    ONE_ERROR_VALIDATION_SIZE_IS_NULLPTR = 1019,
    ONE_ERROR_VALIDATION_VAL_IS_NULLPTR = 1020,
    ONE_ERROR_VALIDATION_VAL_SIZE_IS_TOO_SMALL = 1021,
    ONE_ERROR_VALIDATION_VERSION_IS_NULLPTR = 1022
} OneError;

ONE_EXPORT bool one_is_error(OneError err);

// Given a OneError, returns a string matching the symbol name, e.g.
// error_text(ONE_ERROR_CONNECTION_INVALID_MESSAGE_HEADER) will return
// "ONE_ERROR_CONNECTION_INVALID_MESSAGE_HEADER".
ONE_EXPORT const char *one_error_text(OneError);

#ifdef __cplusplus
};
#endif
