#include <one/ping/error.h>

#include <one/ping/allocator.h>

#include <unordered_map>

// Util that replaces the given symbol with a pair of it and its string
// representation.
#define I3D_PING_ERROR_SYMBOL_STRING_PAIR(e) e, #e

namespace i3d {
namespace ping {

const char *error_text(I3dPingError err) {
    static std::unordered_map<I3dPingError, const char *> lookup = {
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_NONE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_VALIDATION_PARAM_IS_NULLPTR)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_VALIDATION_BUFFER_IS_TOO_SMALL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_DATA_PARSE_FAILED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_DATA_JSON_PAYLOAD_IS_INVALID)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_DATA_JSON_SERVER_INFORMATION_IS_INVALID)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SITES_GETTER_NOT_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SITES_GETTER_ALREADY_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SITES_GETTER_CALLBACK_IS_NULLPTR)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SITES_GETTER_ALLOCATION_FAILED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SITES_GETTER_UNKWON_STATUS)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SITES_GETTER_HTTP_GET_CALLBACK_NOT_SET)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PING_SITE_POS_OUT_OF_RANGE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PING_SITE_IP_POS_OUT_OF_RANGE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_IP_LIST_POS_IS_OUT_OF_RANGE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_IP_LIST_ALLOCATION_FAILED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_CREATION_FAIL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SOCKET_TTL_SET_SOCKET_OPTION_FAIL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_SYSTEM_CLEANUP_FAIL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_INVALID_IPV4)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_SEND_FAIL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SOCKET_RECEIVE_BUFFER_TOO_SMALL)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_RECEIVE_ERROR)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_RECEIVE_TOO_FEW_BYTES)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SOCKET_RECEIVE_DESTINATION_UNREACHABLE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SOCKET_RECEIVE_UNKNOWN_ICMP_PACKET_TYPE)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_RECEIVE_TTL_EXPIRED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_INVALID_TIME)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_ALREADY_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_NOT_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_PING_NOT_SENT)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_UNKNOWN_STATUS)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(
            I3D_PING_ERROR_SOCKET_INVALID_SEQUENCE_NUMBER)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_SELECT_FAILED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_NOT_READY)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_CANNOT_BE_RESET)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_SOCKET_INVALID_REPLY)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGER_DIVISION_BY_ZERO)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGER_INVALID_TIME)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGER_IS_UNINITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGERS_NOT_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGERS_ALREADY_INITIALIZED)},
        {I3D_PING_ERROR_SYMBOL_STRING_PAIR(I3D_PING_ERROR_PINGERS_POS_IS_OUT_OF_RANGE)}};
    auto it = lookup.find(err);
    if (it == lookup.end()) {
        return "";
    }
    return it->second;
}

}  // namespace ping
}  // namespace i3d
